LogIn: log in
LogOut: log out
LoggedAs: logged as
CreateChallenge: add a challenge
Name: name
PublicUrl: public repo (URL)
PrivateUrl: private repo (URL)
Branch: branch
Add: Add!
ListChallenges: list challenges
SubmitSolution: Submit a solution to the challenge
Submit: Submit
SubmissionUrl: Submission repo URL
SubmissionBranch: Submission repo branch
SubmissionDescription: Submission description
SubmissionTags: Submission tags
YourAccount: your account
AboutMe: about me
AccountName: name
AccountNameTooltip: your human-readable name (to be shown on the leaderboard)
Id: ID
IdTooltip: to be used in the URLs for your repos (only lower-case letters, digits or hyphens, must start with a lower-case letter), once set cannot be changed!
SshPubKey: your SSH public key
SshPubKeyTooltip: needed if you want to access repos hosted on Gonito.net (usually ".ssh/id_rsa.pub" in your home directory after you generated private/public key pair)
Home: home
Search: search
GitCommitSha1: Git commit SHA1 hash
CommentText: Write a comment
Send: Send
Avatar: avatar
About: about
Password: enter a new password for your account
EMail: e-mail
CreateResetLink: create reset link
LinkWrongOrExpired: Link wrong or expired, please ask the site admin again
TagName: tag
TagDescription: description
ListTags: list tags
AchievementName: achievement name
AchievementDescription: optional description
AchievementDeadlineDay: achievement deadline day
AchievementDeadlineTime: achievement deadline hour
AchievementMaxWinners: maximum number of submitters
AchievementTags: tags required for an achievement
Achievements: achievements
AchievementPoints: points
WantToBeAnonimised: I want to stay anonymous for other user of Gonito.net
YourScore: your score
PasswordForNewAccount: enter a password for your new account
