LogIn: log in
LogOut: log out
LoggedAs: logged as
CreateChallenge: add a challenge
Name: name
PublicUrl: public repo (URL)
PrivateUrl: private repo (URL)
Branch: branch
Add: Add!
ListChallenges: list challenges
SubmitSolution: Submit a solution to the challenge
Submit: Submit
SubmissionUrl: Submission repo URL
SubmissionBranch: Submission repo branch
SubmissionDescription: Submission description
YourAccount: your account
AboutMe: about me
AccountName: name
Id: ID
SshPubKey: your SSH public key
Home: home
Search: search
GitCommitSha1: Git commit SHA1 hash
CommentText: Write a comment
Send: Send
