LogIn: log in
LogOut: log out
LoggedAs: logged as
CreateChallenge: add a challenge
Name: name
PublicUrl: public repo (URL)
PrivateUrl: private repo (URL)
Branch: branch
Add: Add!
ListChallenges: challenges
SubmitSolution: Submit a solution to the challenge
Submit: Submit
SubmissionUrl: Submission repo URL
SubmissionBranch: Submission repo branch
SubmissionDescription: Submission description
SubmissionTags: Submission tags
YourAccount: your account
AboutMe: about me
AccountName: name
AccountNameTooltip: your human-readable name (to be shown on the leaderboard)
Id: ID
IdTooltip: to be used in the URLs for your repos (only lower-case letters, digits or hyphens, must start with a lower-case letter), once set cannot be changed!
SshPubKey: your SSH public key
SshPubKeyTooltip: needed if you want to access repos hosted on Gonito.net (usually ".ssh/id_rsa.pub" in your home directory after you generated private/public key pair)
Home: home
Search: search
GitCommitSha1: Git commit SHA1 hash
CommentText: Write a comment
Send: Send
Avatar: avatar
About: about
Password: enter a new password for your account
EMail: e-mail
CreateResetLink: create reset link
LinkWrongOrExpired: Link wrong or expired, please ask the site admin again
TagName: tag
TagDescription: description
ListTags: tags
AchievementName: achievement name
AchievementDescription: optional description
AchievementDeadlineDay: achievement deadline day
AchievementDeadlineTime: achievement deadline hour
AchievementMaxWinners: maximum number of submitters
AchievementTags: tags required for an achievement
Achievements: achievements
AchievementPoints: points
WantToBeAnonimised: I want to stay anonymous for other user of Gonito.net
YourScore: your score
PasswordForNewAccount: enter a password for your new account
SubmissionDescriptionTooltip: the first non-empty line of the commit message will be used, if this is left empty
Challenge: challenge
Course: course
CourseOptional: course (optional)
AddExtraPoints: add points freely
ExtraPointsPoints: Points to be added
ExtraPointsDescription: Describe why they are added
User: User
Manage: manage
Presentation: presentation
GonitoInClass: Gonito in class
GitAnnexRemote: git-annex remote (if needed)
SubmissionGitAnnexRemote: git-annex remote specification (if needed)
RemoveSubmission: remove submission
RestoreSubmission: restore submission
ParameterName: parameter name
ParameterValue: parameter value
ChallengeName: computer-friendly name ("slug")
ChallengeNameTooltip: to be used in the URLs (only lower-case letters, digits or hyphens, must start with a lower-case letter), once set cannot be changed!
FilterCondition: filter condition
FilterConditionTooltip: the condition used to pre-select all submission — an extra graph will be drawed for all submissions matching this condition (not necessarily the target condition)
TargetCondition: target condition
TargetConditionTooltip: the condition which is required for a submission to be considered for realising the target
TargetDeadlineDay: target day
TargetDeadlineTime: target time
TargetValue: target value to be reached before the target date
Test: test
Dashboard: dashboard
TargetName: target name
ShowArchivedChallenges: show archived challenges
CoursesITeach: courses I teach
MajorChange: major change
MinorChange: minor change
Patch: patch
ChangeType: change type
Update: Update
ChallengeDeadlineDay: challenge deadline day
ChallengeDeadlineTime: challenge deadline time
ChallengeDeadlineTooltip: no submissions will be accepted after the deadline; this can be used for organizing competitions set in time
WritingPapers: writing papers with Gonito
UserIdentifier: user login/identifier
AltRepoScheme: alternative git repo scheme (URL without the challenge name pointing to some external server)
AltRepoSchemeTooltip: set this if you want to use an alternative git server for all your submissions
